class GlinerConfig:
    def __init__(self):
        self.model_path = "gliner/gliner_multi_pii-v1"

        # Presidio formatında entity türleri
        self.entity_types = [
            "PERSON",
            "GENDER",
            "MARITAL_STATUS",
            "EMAIL_ADDRESS",
            "ADDRESS",
            "MEDICAL_CONDITION",
            "BLOOD_TYPE",
            "RELIGION",
            "POLITICAL_VIEW",
            "ORGANIZATION",
            "SALARY",
            "OCCUPATION",
            "IBAN",
            "TCKN",
            "PHONE_NUMBER",
            "CREDIT_CARD_NUMBER",
            "SOCIAL_SECURITY_NUMBER",
            "DATE_OF_BIRTH",
            "BANK_ACCOUNT_NUMBER",
            "IP_ADDRESS",
            "CREDIT_CARD_EXPIRATION_DATE",
            "CVV",
            "ZIP_CODE",
            "CVC",
            "TRANSACTION_NUMBER",
            "LICENSE_PLATE_NUMBER"
            "SERIAL_NUMBER",
        ]

        # Presidio → GLiNER format mapping
        self.entity_mapping = {
            "person": "PERSON",
            "gender": "GENDER",
            "marital status": "MARITAL_STATUS",
            "email address": "EMAIL_ADDRESS",
            "address": "ADDRESS",
            "medical condition": "MEDICAL_CONDITION",
            "blood type": "BLOOD_TYPE",
            "religion": "RELIGION",
            "political view": "POLITICAL_VIEW",
            "organization": "ORGANIZATION",
            "salary": "SALARY",
            "occupation": "OCCUPATION",
            "iban": "IBAN",
            "tckn": "TCKN",
            "phone number": "PHONE_NUMBER",
            "credit card number": "CREDIT_CARD_NUMBER",
            "social security number": "SOCIAL_SECURITY_NUMBER",
            "date of birth": "DATE_OF_BIRTH",
            "bank account number": "BANK_ACCOUNT_NUMBER",
            "ip address": "IP_ADDRESS",
            "credit card expiration date": "CREDIT_CARD_EXPIRATION_DATE",
            "cvv": "CVV",
            "zip code": "ZIP_CODE",
            "cvc": "CVC",
            "transaction number": "TRANSACTION_NUMBER",
            "license plate number": "LICENSE_PLATE_NUMBER",
            "serial number": "SERIAL_NUMBER"
        }

        # Belirli terimleri içeren yanlış pozitifleri engellemek için deny list
        self.deny_list = {
            "person name": ["isim", "ad", "soyad"],
            "gender": ["cinsiyet", "erkek", "kadın"],
            "marital status": ["evli", "bekar", "boşanmış"],
            "email address": ["e-posta", "mail", "adres"],
            "address": ["adres", "konum", "yer"],
            "medical condition": ["hastalık", "rahatsızlık", "durum"],
            "blood type": ["kan", "grubu", "tip"],
            "religion": ["din", "inanç", "mezhep"],
            "political view": ["görüş", "ideoloji", "düşünce"],
            "organization": ["kurum", "şirket", "dernek"],
            "salary": ["maaş", "ücret", "kazanç"],
            "occupation": ["meslek", "iş", "pozisyon"],
        }

        # Her entity türü için örnek cümleler
        self.examples = {
            "person name": [
                "Ali is a teacher",
                "Ayşe met with John",
                "Mehmet and Elif are siblings",
                "Ali öğretmen olarak çalışıyor.",
                "Ayşe, Elif ile buluştu.",
                "Mehmet ve Zeynep kardeştir.",
            ],
            "gender": [
                "His gender is male",
                "She identifies as female",
                "They are non-binary",
                "Cinsiyeti erkektir.",
                "Kadın olduğunu belirtti.",
                "Kendini non-binary olarak tanımlıyor.",
            ],
            "marital status": [
                "He is married",
                "She is divorced",
                "They are single",
                "Evli bir bireydir.",
                "Boşanmış durumda.",
                "Bekar olduğunu söyledi.",
            ],
            "email address": [
                "Her email is ayse@example.com",
                "Contact him at ali@gmail.com",
                "E-posta adresi ayse@example.com'dur.",
                "Bana ali@gmail.com üzerinden ulaşabilirsiniz.",
                "İletişim için mehmet@firma.com adresini kullanın.",
            ],
            "address": [
                "123 Main Street, New York",
                "He lives in Kadıköy",
                "Fatih Mahallesi, İstanbul'da yaşıyor.",
                "Adres bilgisi: 123 Main Street, New York.",
            ],
            "medical condition": [
                "He suffers from diabetes",
                "She has asthma",
                "Diyabet hastasıdır.",
                "Astım problemi var.",
                "Hipertansiyon teşhisi kondu.",
            ],
            "blood type": [
                "His blood type is AB+",
                "She is O negative",
                "Kan grubu AB+.",
                "O negatif olduğunu söyledi.",
                "A tipi kana sahip.",
            ],
            "religion": [
                "Ali is Muslim",
                "She converted to Christianity",
                "Ali Müslümandır.",
                "Hristiyanlığa geçti.",
                "Budist inancına sahiptir.",
            ],
            "political view": [
                "He supports socialism",
                "She is a conservative",
                "Sosyalist görüşleri savunuyor.",
                "Muhafazakâr olduğunu belirtti.",
                "Liberal düşüncelere sahip.",
            ],
            "organization": [
                "He works at Microsoft",
                "She is part of UNICEF",
                "Microsoft'ta çalışıyor.",
                "UNICEF üyesi.",
                "Eğitim-Sen sendikasına bağlı.",
            ],
            "salary": [
                "She earns 5,000 USD monthly",
                "His salary is 15,000 TL",
                "Maaşı 15.000 TL'dir.",
                "Aylık 5.000 USD kazanıyor.",
                "Geliri 20.000 TL civarında.",
            ],
            "occupation": [
                "He is a software engineer",
                "She works as a nurse",
                "Yazılım mühendisi olarak çalışıyor.",
                "Hemşire olarak görev yapıyor.",
                "Avukatlık yapıyor.",
            ],
        }
